# Generated by Django 3.0.4 on 2021-05-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSignalTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=1)),
                ('beep_signal', models.CharField(max_length=1)),
                ('atomizer_signal', models.CharField(max_length=1)),
                ('water_pump_signal', models.CharField(max_length=1)),
                ('heat_signal', models.CharField(max_length=1)),
                ('fan_signal', models.CharField(max_length=1)),
                ('atomizer_breakdown_signal', models.CharField(max_length=1)),
                ('water_pump_breakdown_signal', models.CharField(max_length=1)),
                ('heat_breakdown_signal', models.CharField(max_length=1)),
                ('fan_breakdown_signal', models.CharField(max_length=1)),
                ('dht11_breakdown_signal', models.CharField(max_length=1)),
                ('anemograph_breakdown_signal', models.CharField(max_length=1)),
                ('ccs811_breakdown_signal', models.CharField(max_length=1)),
                ('control_type', models.CharField(max_length=1)),
                ('op_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FruitControlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=5)),
                ('control_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FruitEnvironmentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=5)),
                ('fruit_temperature_max', models.CharField(max_length=3)),
                ('fruit_temperature_min', models.CharField(max_length=3)),
                ('fruit_humidity_max', models.CharField(max_length=2)),
                ('fruit_humidity_min', models.CharField(max_length=2)),
                ('fruit_wind_speed_max', models.CharField(max_length=2)),
                ('fruit_wind_speed_min', models.CharField(max_length=2)),
                ('fruit_carbon_dioxide_max', models.CharField(max_length=4)),
                ('fruit_carbon_dioxide_min', models.CharField(max_length=4)),
                ('fruit_PVOC_max', models.CharField(max_length=4)),
                ('fruit_PVOC_min', models.CharField(max_length=4)),
                ('op_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorDataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=1)),
                ('temperature_data', models.CharField(max_length=3)),
                ('humidity_data', models.CharField(max_length=2)),
                ('wind_speed_data', models.CharField(max_length=2)),
                ('carbon_dioxide_data', models.CharField(max_length=4)),
                ('PVOC_data', models.CharField(max_length=4)),
                ('op_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageMaintainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=300)),
                ('remark', models.CharField(max_length=300)),
                ('op_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=10)),
                ('user_mail', models.CharField(max_length=100, null=True)),
                ('user_phone', models.CharField(max_length=20, null=True)),
                ('user_type', models.CharField(max_length=1)),
                ('remark', models.CharField(max_length=500, null=True)),
                ('op_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
